services:
  - type: web
    name: miguel-render-1
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    healthCheckPath: "/healthz"
    envVars:
      - key: PORT
        value: "3000"

      # Cloudflare R2 (API S3)
      - key: CF_R2_ACCESS_KEY_ID
        sync: false
      - key: CF_R2_SECRET_ACCESS_KEY
        sync: false
      - key: CF_R2_BUCKET
        value: "miguelcomprovante"
      - key: CF_R2_ENDPOINT
        value: "https://SEU-ID.r2.cloudflarestorage.com"

