services:
  - type: web
    name: miguel-render-1
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: S3_BUCKET
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_REGION
        value: auto
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
